apiVersion: apps/v1
kind: Deployment
metadata:
  name: coupon-service
  namespace: ecommerce-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: coupon-service
  template:
    metadata:
      labels:
        app: coupon-service
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - node02
      containers:
        - name: coupon-service
          image: pinocure717/ecommerce-coupon-service:latest
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql-coupon-service.ecommerce-infra.svc.cluster.local:3306/coupon_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
            - name: SPRING_DATASOURCE_USERNAME
              value: "ruang"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "ruang"
            - name: SPRING_REDIS_HOST
              value: "redis-service.ecommerce-infra.svc.cluster.local"
            - name: SPRING_REDIS_PORT
              value: "6379"