apiVersion: apps/v1
kind: Deployment
metadata:
  name: balance-service
  namespace: ecommerce-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: balance-service
  template:
    metadata:
      labels:
        app: balance-service
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - node01
      containers:
        - name: balance-service
          image: pinocure717/ecommerce-balance-service:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql-balance-service.ecommerce-infra.svc.cluster.local:3306/balance_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
            - name: SPRING_DATASOURCE_USERNAME
              value: "ruang"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "ruang"
            - name: SPRING_REDIS_HOST
              value: "redis-service.ecommerce-infra.svc.cluster.local"
            - name: SPRING_REDIS_PORT
              value: "6379"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka.ecommerce-infra.svc.cluster.local:9092"
            - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
              value: "org.apache.kafka.common.serialization.StringSerializer"
            - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
              value: "org.springframework.kafka.support.serializer.JsonSerializer"
            - name: SPRING_KAFKA_CONSUMER_GROUP_ID
              value: "balance-service-group"
            - name: SPRING_KAFKA_CONSUMER_KEY_DESERIALIZER
              value: "org.apache.kafka.common.serialization.StringDeserializer"
            - name: SPRING_KAFKA_CONSUMER_VALUE_DESERIALIZER
              value: "org.springframework.kafka.support.serializer.JsonDeserializer"
            - name: SPRING_KAFKA_CONSUMER_PROPERTIES_SPRING_JSON_TRUSTED_PACKAGES
              value: "*"