apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: ecommerce-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - node01
      containers:
        - name: user-service
          image: pinocure717/ecommerce-user-service:latest
          ports:
            - containerPort: 8084
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql-user-service.ecommerce-infra.svc.cluster.local:3306/user_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
            - name: SPRING_DATASOURCE_USERNAME
              value: "ruang"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "ruang"