apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-balance
  namespace: ecommerce-infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-balance
  template:
    metadata:
      labels:
        app: mysql-balance
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          args:
            - "--bind-address=0.0.0.0"
            - "--default-authentication-plugin=mysql_native_password"
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
            - name: MYSQL_DATABASE
              value: "balance_db"
            - name: MYSQL_USER
              value: "ruang"
            - name: MYSQL_PASSWORD
              value: "ruang"
            - name: MYSQL_ROOT_HOST
              value: "%"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-balance-service
  namespace: ecommerce-infra
spec:
  selector:
    app: mysql-balance
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-coupon
  namespace: ecommerce-infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-coupon
  template:
    metadata:
      labels:
        app: mysql-coupon
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          args:
            - "--bind-address=0.0.0.0"
            - "--default-authentication-plugin=mysql_native_password"
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
            - name: MYSQL_DATABASE
              value: "coupon_db"
            - name: MYSQL_USER
              value: "ruang"
            - name: MYSQL_PASSWORD
              value: "ruang"
            - name: MYSQL_ROOT_HOST
              value: "%"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-coupon-service
  namespace: ecommerce-infra
spec:
  selector:
    app: mysql-coupon
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-order
  namespace: ecommerce-infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-order
  template:
    metadata:
      labels:
        app: mysql-order
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          args:
            - "--bind-address=0.0.0.0"
            - "--default-authentication-plugin=mysql_native_password"
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
            - name: MYSQL_DATABASE
              value: "order_db"
            - name: MYSQL_USER
              value: "ruang"
            - name: MYSQL_PASSWORD
              value: "ruang"
            - name: MYSQL_ROOT_HOST
              value: "%"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-order-service
  namespace: ecommerce-infra
spec:
  selector:
    app: mysql-order
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-product
  namespace: ecommerce-infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-product
  template:
    metadata:
      labels:
        app: mysql-product
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          args:
            - "--bind-address=0.0.0.0"
            - "--default-authentication-plugin=mysql_native_password"
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
            - name: MYSQL_DATABASE
              value: "product_db"
            - name: MYSQL_USER
              value: "ruang"
            - name: MYSQL_PASSWORD
              value: "ruang"
            - name: MYSQL_ROOT_HOST
              value: "%"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-product-service
  namespace: ecommerce-infra
spec:
  selector:
    app: mysql-product
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-user
  namespace: ecommerce-infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-user
  template:
    metadata:
      labels:
        app: mysql-user
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          args:
            - "--bind-address=0.0.0.0"
            - "--default-authentication-plugin=mysql_native_password"
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
            - name: MYSQL_DATABASE
              value: "user_db"
            - name: MYSQL_USER
              value: "ruang"
            - name: MYSQL_PASSWORD
              value: "ruang"
            - name: MYSQL_ROOT_HOST
              value: "%"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          emptyDir: {}