apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  namespace: ecommerce-app
spec:
  selector:
    app: api-gateway
  ports:
    - port: 8090
      targetPort: 8090
      nodePort: 30090
  type: NodePort