server:
  port: 8080

spring:
  application:
    name: order-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://mysql-order:3306/order_db}
    username: ${SPRING_DATASOURCE_USERNAME:ruang}
    password: ${SPRING_DATASOURCE_PASSWORD:ruang}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 250000
      connection-timeout: 5000
      maximum-pool-size: 5
      minimum-idle: 1

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQL8Dialect

  data:
    redis:
      host: ${SPRING_REDIS_HOST:redis}
      port: ${SPRING_REDIS_PORT:6379}
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 2

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: ${SPRING_KAFKA_PRODUCER_KEY_SERIALIZER:org.apache.kafka.common.serialization.StringSerializer}
      value-serializer: ${SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER:org.springframework.kafka.support.serializer.JsonSerializer}
    consumer:
      group-id: ${SPRING_KAFKA_CONSUMER_GROUP_ID:order-service-group}
      key-deserializer: ${SPRING_KAFKA_CONSUMER_KEY_DESERIALIZER:org.apache.kafka.common.serialization.StringDeserializer}
      value-deserializer: ${SPRING_KAFKA_CONSUMER_VALUE_DESERIALIZER:org.springframework.kafka.support.serializer.JsonDeserializer}
      properties:
        spring:
          json:
            trusted:
              packages: ${SPRING_KAFKA_CONSUMER_PROPERTIES_SPRING_JSON_TRUSTED_PACKAGES:*}

services:
  balance:
    url: ${SERVICES_BALANCE_URL:http://balance-service:8081}
  coupon:
    url: ${SERVICES_COUPON_URL:http://coupon-service:8082}
  product:
    url: ${SERVICES_PRODUCT_URL:http://product-service:8083}
  user:
    url: ${SERVICES_USER_URL:http://user-service:8084}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.hhplus.ecommerce: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"