{{- range .Values.mysql.databases }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .service }}
  namespace: {{ $.Values.global.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .service }}
  template:
    metadata:
      labels:
        app: {{ .service }}
    spec:
      containers:
        - name: mysql
          image: {{ $.Values.mysql.image }}
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "{{ $.Values.mysql.credentials.password }}"
            - name: MYSQL_DATABASE
              value: "{{ .name }}"
            - name: MYSQL_USER
              value: "{{ $.Values.mysql.credentials.username }}"
            - name: MYSQL_PASSWORD
              value: "{{ $.Values.mysql.credentials.password }}"
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .service }}
  namespace: {{ $.Values.global.namespace }}
spec:
  selector:
    app: {{ .service }}
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP
  {{- end }}