apiVersion: v1
kind: ConfigMap
metadata:
  name: zookeeper-config
  namespace: {{ .Values.global.namespace }}
data:
  ZOOKEEPER_CLIENT_PORT: "{{ .Values.zookeeper.port }}"
  ZOOKEEPER_TICK_TIME: "2000"
  ZOOKEEPER_SYNC_LIMIT: "5"
  ZOOKEEPER_INIT_LIMIT: "10"
  ZOOKEEPER_MAX_CLIENT_CNXNS: "60"
  ZOOKEEPER_AUTOPURGE_SNAP_RETAIN_COUNT: "3"
  ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL: "24"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
  namespace: {{ .Values.global.namespace }}
spec:
  serviceName: zookeeper
  replicas: {{ .Values.zookeeper.replicas }}
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: {{ .Values.zookeeper.image }}
          ports:
            - containerPort: {{ .Values.zookeeper.port }}
          envFrom:
            - configMapRef:
                name: zookeeper-config
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: zookeeper
  ports:
    - port: {{ .Values.zookeeper.port }}
      targetPort: {{ .Values.zookeeper.port }}
  type: ClusterIP