apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: ecommerce-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - node02
      containers:
        - name: order-service
          image: pinocure717/ecommerce-order-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql-order-service.ecommerce-infra.svc.cluster.local:3306/order_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
            - name: SPRING_DATASOURCE_USERNAME
              value: "ruang"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "ruang"
            - name: SPRING_REDIS_HOST
              value: "redis-service.ecommerce-infra.svc.cluster.local"
            - name: SPRING_REDIS_PORT
              value: "6379"
            - name: SERVICES_BALANCE_URL
              value: "http://balance-service.ecommerce-app.svc.cluster.local:8081"
            - name: SERVICES_COUPON_URL
              value: "http://coupon-service.ecommerce-app.svc.cluster.local:8082"
            - name: SERVICES_PRODUCT_URL
              value: "http://product-service.ecommerce-app.svc.cluster.local:8083"
            - name: SERVICES_USER_URL
              value: "http://user-service.ecommerce-app.svc.cluster.local:8084"
